#!/usr/bin/env python3
# ============================================================
# DRILLPULSE — Frontier Exploration Node
# ============================================================
# Evaluates 2D Occupancy Grid maps generated by SLAM Toolbox.
# Identifies frontier cells on the boundary between free space and
# unknown territory, filters out obstacles and boundaries, tracks
# unreachable candidate blacklists, respects low-battery returns,
# and publishes exploration targets to Nav2 (/goal_pose).
# ============================================================

import math
import time
import numpy as np
import rclpy
from rclpy.node import Node
from nav_msgs.msg import OccupancyGrid, Odometry
from geometry_msgs.msg import PoseStamped
from sensor_msgs.msg import BatteryState
from drillpulse_msgs.msg import MissionState


class FrontierExplorationNode(Node):
    """Frontier detection, candidate gating, and exploration coordinator."""

    def __init__(self):
        super().__init__('frontier_exploration_node')

        self.declare_parameter('min_frontier_dist', 1.0)
        self.declare_parameter('max_frontier_dist', 25.0)
        self.declare_parameter('goal_tolerance', 0.6)
        self.declare_parameter('cycle_period_sec', 3.0)

        self.min_dist = float(self.get_parameter('min_frontier_dist').value)
        self.max_dist = float(self.get_parameter('max_frontier_dist').value)
        self.goal_tol = float(self.get_parameter('goal_tolerance').value)
        cycle_period = float(self.get_parameter('cycle_period_sec').value)

        self.map_msg = None
        self.rover_x = 0.0
        self.rover_y = 0.0
        self.exploration_active = False
        self.mission_state_str = 'IDLE'
        self.battery_low = False

        self.current_goal = None
        self.last_goal_time = 0.0
        self.failed_goals_blacklist = []  # List of (x, y, timestamp)

        # Publishers
        self.goal_pub = self.create_publisher(PoseStamped, '/goal_pose', 10)

        # Subscriptions
        self.map_sub = self.create_subscription(OccupancyGrid, '/map', self.on_map, 10)
        self.odom_sub = self.create_subscription(Odometry, '/odom', self.on_odom, 10)
        self.state_sub = self.create_subscription(MissionState, '/rover/mission_state', self.on_state, 10)
        self.battery_sub = self.create_subscription(BatteryState, '/rover/battery', self.on_battery, 10)

        self.timer = self.create_timer(cycle_period, self.exploration_cycle)
        self.get_logger().info('Frontier Exploration Node active.')

    def on_odom(self, msg: Odometry):
        self.rover_x = msg.pose.pose.position.x
        self.rover_y = msg.pose.pose.position.y

    def on_map(self, msg: OccupancyGrid):
        self.map_msg = msg

    def on_state(self, msg: MissionState):
        self.mission_state_str = msg.current_state
        # Only active when in UNEXPLORED job and not currently returning
        is_unexplored = (msg.active_job == 'UNEXPLORED')
        not_returning = not msg.current_state.startswith('RETURN')
        self.exploration_active = is_unexplored and not_returning

    def on_battery(self, msg: BatteryState):
        self.battery_low = (msg.voltage < 10.5 or msg.percentage < 15.0)

    def is_blacklisted(self, x: float, y: float) -> bool:
        now = time.time()
        # Keep blacklist for 60 seconds
        self.failed_goals_blacklist = [b for b in self.failed_goals_blacklist if now - b[2] < 60.0]
        for bx, by, _ in self.failed_goals_blacklist:
            if math.hypot(bx - x, by - y) < 1.0:
                return True
        return False

    def exploration_cycle(self):
        if not self.exploration_active or self.battery_low or self.map_msg is None:
            return

        now = time.time()
        # If currently tracking a goal that has not timed out (15s) and rover is not yet close, continue
        if self.current_goal and (now - self.last_goal_time < 15.0):
            dist_to_goal = math.hypot(self.current_goal[0] - self.rover_x, self.current_goal[1] - self.rover_y)
            if dist_to_goal > self.goal_tol:
                return
            else:
                self.get_logger().info(f'Reached frontier goal ({self.current_goal[0]:.2f}, {self.current_goal[1]:.2f}).')
                self.current_goal = None

        # If goal was active and timed out without reaching, add to blacklist
        if self.current_goal and (now - self.last_goal_time >= 15.0):
            self.get_logger().warn(
                f'Frontier goal ({self.current_goal[0]:.2f}, {self.current_goal[1]:.2f}) unreachable/timed out. Blacklisting.'
            )
            self.failed_goals_blacklist.append((self.current_goal[0], self.current_goal[1], now))
            self.current_goal = None

        info = self.map_msg.info
        width, height = info.width, info.height
        res = info.resolution
        ox, oy = info.origin.position.x, info.origin.position.y

        if width < 5 or height < 5:
            return

        try:
            grid = np.array(self.map_msg.data, dtype=np.int8).reshape((height, width))
        except ValueError:
            return

        candidates = []

        # Stride through occupancy grid to find frontiers
        for r in range(2, height - 2, 3):
            for c in range(2, width - 2, 3):
                # Cell must be definitely free space
                cell_val = grid[r, c]
                if 0 <= cell_val <= 20:
                    # Check 4-connected neighbors for unknown space (-1)
                    neighbors = (grid[r+1, c], grid[r-1, c], grid[r, c+1], grid[r, c-1])
                    if -1 in neighbors:
                        # Ensure cell is not right next to an obstacle (> 50)
                        extended_neighbors = grid[max(0, r-2):min(height, r+3), max(0, c-2):min(width, c+3)]
                        if np.any(extended_neighbors > 50):
                            continue  # Skip cells too close to obstacles

                        wx = ox + (c + 0.5) * res
                        wy = oy + (r + 0.5) * res

                        if self.is_blacklisted(wx, wy):
                            continue

                        d = math.hypot(wx - self.rover_x, wy - self.rover_y)
                        if self.min_dist <= d <= self.max_dist:
                            candidates.append((wx, wy, d))

        if candidates:
            # Sort candidates by distance (closest frontier first)
            candidates.sort(key=lambda x: x[2])
            tx, ty = candidates[0][0], candidates[0][1]
            self.current_goal = (tx, ty)
            self.last_goal_time = now

            goal = PoseStamped()
            goal.header.stamp = self.get_clock().now().to_msg()
            goal.header.frame_id = 'map'
            goal.pose.position.x = float(tx)
            goal.pose.position.y = float(ty)
            goal.pose.position.z = 0.0

            # Orientation facing towards the target from current rover position
            angle = math.atan2(ty - self.rover_y, tx - self.rover_x)
            goal.pose.orientation.z = math.sin(angle * 0.5)
            goal.pose.orientation.w = math.cos(angle * 0.5)

            self.goal_pub.publish(goal)
            self.get_logger().info(f'Selected frontier exploration target: ({tx:.2f}, {ty:.2f}) [dist: {candidates[0][2]:.2f}m]')
        else:
            self.get_logger().info('No valid reachable frontier candidates found (Exploration complete or blocked).')


def main(args=None):
    rclpy.init(args=args)
    node = FrontierExplorationNode()
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main()
